/**
 * AUTO-GENERATED by kysely-codegen
 * DO NOT EDIT - run `bun db:codegen` after migrations
 *
 * This file is a placeholder until you run your first migration.
 */

export type Json = unknown

// Empty database type - add tables via migrations
export interface DB {}
